### ISSUE TITLE
is 优化

### ISSUE THREAD

**Issue by ywnkm** [Serendipithub/kotlin-pattern-matching#1]
目前 is 居然要传一个新对象
https://github.com/Serendipithub/kotlin-pattern-matching/blob/06d54cf0cc84e657ecc15e56b3911d467347a198/MatchPatternX.kt#L100-L104

可以在 MatchPatternScope 中保存一个 KClass 对象，通过 reified 泛型传递 KClass 对象，然后用 kclass.isSubclassOf(kclass) 确保子类也能实现匹配

**Comment by Serendipithub** [comment]
感谢您提交的ISSUE, 所诉建议将会被采取.

**Comment by Serendipithub** [comment]
已更新, 现在不需要传入新的对象.
并且添加了else分支操作用于匹配穷举性
